### ISSUE TITLE
Speed-up ordinals indexing

### ISSUE THREAD

**Issue by mwalol** [hirosystems/bitcoin-indexer#124]
having the bitcoin node and the chainhook on the same machine
we should have a flag dev to read the blockchain data from the disk instead of rpc for fast syncing
once's synced we have choice to read from rpc

**Comment by lgalabru** [comment]
Hey @mwalol! Thanks for opening this issue, this is indeed a concern on my end, and we'll be doing a new pass on indexing speed in the next weeks.

**Comment by lgalabru** [comment]
Next iteration:
Pass 1: Download and compress blocks (out of order)
Pass 2: Identify Inscriptions and Compute ordinal numbers (out of order)
Pass 3: Compute Transfers, Inscription numbers, identify eventual curse types (in order)

**Comment by smcclellan** [comment]
In scope for this ticket is Pass 1 from above.

**Comment by sabbyanandan** [comment]
Hi, @mwalol! Your speed-relatead observation and the specifics behind how you're trying to use `hord` made be curious. I would love to learn more about your use of `hord` and use cases. 

Can you point me to any details where I can learn/educate myself? It'll also help us think through other feature-toggles and the overall `hord`'s DevEx. Alternatively, I would love to also talk and exchange ideas: https://calendly.com/sabbyanandan/platform-office-hours

**Comment by lgalabru** [comment]
A bunch of changes recently merged in `develop`. Speed will always be an area of R&D, but the next lowest hanging fruit might be on devops side.
