### ISSUE TITLE
get inscription content error

### ISSUE THREAD

**Issue by skyrover7** [hirosystems/bitcoin-indexer#136]
I am receiving `error not found` on this request, but the ID is correct and does indeed exist

GET on this link: https://api.hiro.so/ordinals/v1/inscriptions/d88cfc96b40111d142dbdd8e855c3dc8428d2562567bb03b41f8d3ab0d98eedai0/content

Data does indeed exist: https://ordinals.com/inscription/d88cfc96b40111d142dbdd8e855c3dc8428d2562567bb03b41f8d3ab0d98eedai0

**Comment by janniks** [comment]
Thanks for the report. This inscription wasn't indexed for some reason.
We will look into it on the API/chainhook side of things 🙏

**Comment by smcclellan** [comment]
@skyrover7 This will be fixed later today when the latest environment is active.

**Comment by lgalabru** [comment]
Addressed with latest deployment
