### ISSUE TITLE
btcoind generate block, hord server do not start scan the latest block

### ISSUE THREAD

**Issue by bingryan** [hirosystems/bitcoin-indexer#141]
Hi, 

After `hord service start --config-path=./Hord.toml` scan the lastest block. and get info:
<img width="775" alt="image" src="https://github.com/hirosystems/ordhook/assets/41174435/a035d5ed-95eb-4ab9-b18b-eaedf411c004">
then I make btcoind  generate new block(generate 10 blocks), but hord not start scan the lastest block. 

Is this a BUG or need to use other methods to let hord start scan lastest block(scan the new 10 blocks).

**Comment by bingryan** [comment]
When I restart, it will scan the latest block :) , then  I make btcoind generate new block , hord not start scan the lastest block :)

**Comment by bingryan** [comment]
Why not this logic:: btcoind generates a new block, hord will synchronize the latest block

**Comment by chresko** [comment]
@lgalabru Is this expected behavior?

**Comment by bingryan** [comment]
error by my btcoind client's  zeromq.
