### ISSUE TITLE
CI failing when merging branches 

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/bitcoin-indexer#167]
https://github.com/hirosystems/ordhook/actions/runs/6087613429/job/16516548524

![Screenshot 2023-09-05 at 15 37 45](https://github.com/hirosystems/ordhook/assets/87777/8743b70d-9173-4639-b585-c4939ec37cf8)

**Comment by lgalabru** [comment]
hey @deantchi! it looks like we'll need some additional work on the CI - merging branches leads to failed workflows.

**Comment by aravindgee** [comment]
Fixed - `main` branch had to be created. (Semantic versioning has been been setup to build releases from here)

Thanks Charlie for the help!
