### ISSUE TITLE
Cursed Inscription IDs

### ISSUE THREAD

**Issue by bruffstar** [hirosystems/bitcoin-indexer#181]
I just inscribed some parent/child cursed inscriptions. The ID in the API is ending with `i1` - this makes sense as the child was indeed inscribed on index 1, but in every explorer this does not effect the ID, it should always end in `i0` as far as I am aware. Bug?

![image](https://github.com/hirosystems/ordinals-api/assets/1890098/8a5a33a8-28dd-43bb-9bf9-376f92d836ea)

See here: https://api.hiro.so/ordinals/v1/inscriptions?address=bc1ptsyzdercvzky7z2rxy8rv8njn6mpy5s72r2kgnhhuexk637c22eqz7qga0&limit=60

**Comment by lgalabru** [comment]
Addressed in [v2.0.0](https://github.com/hirosystems/ordhook/releases/tag/v2.0.0)!
