### ISSUE TITLE
`ordhook service start` can silently fail when user's machine "max per-process number of file descriptors" set by `ulimit` is too low

### ISSUE THREAD

**Issue by mefrem** [hirosystems/bitcoin-indexer#194]
**Summary**: User must manually set `ulimit -Sn 10000` so that ordhook process can handle work required when creating tables for ordinals inscription indexes, however both 1) the error messages suggesting a problem are hidden by default and 2) the error messages themselves don't contain or suggest the fix (increasing `ulimit -Sn 10000`).

**Description of problem**: With `ordhook service start` running, this screen would persist (indefinitely?) with no indication that certain indexing actions aren't working:

![screen_shot_2023-10-18_at_10 37 03_pm_720](https://github.com/hirosystems/ordhook/assets/51917427/ba865647-f334-4432-9b1a-d343d58e865b)

These would be the error logs that suggest an error:
![screen_shot_2023-10-18_at_10 43 25_pm_720](https://github.com/hirosystems/ordhook/assets/51917427/1776c0ad-3312-4286-97e0-c09e3b19f0ef)

Solution is to have user manually increase `ulimit -Sn 10000` — maybe create a special class of error message indicating fix required on part of user?

**Comment by taoyouxian** [comment]
> **Summary**: User must manually set `ulimit -Sn 10000` so that ordhook process can handle work required when creating tables for ordinals inscription indexes, however both 1) the error messages suggesting a problem are hidden by default and 2) the error messages themselves don't contain or suggest the fix (increasing `ulimit -Sn 10000`).
> 
> **Description of problem**: With `ordhook service start` running, this screen would persist (indefinitely?) with no indication that certain indexing actions aren't working:
> 
> ![screen_shot_2023-10-18_at_10 37 03_pm_720](https://user-images.githubusercontent.com/51917427/276417432-ba865647-f334-4432-9b1a-d343d58e865b.png)
> 
> These would be the error logs that suggest an error: ![screen_shot_2023-10-18_at_10 43 25_pm_720](https://user-images.githubusercontent.com/51917427/276419001-1776c0ad-3312-4286-97e0-c09e3b19f0ef.png)
> 
> Solution is to have user manually increase `ulimit -Sn 10000` — maybe create a special class of error message indicating fix required on part of user?

![image](https://github.com/hirosystems/ordhook/assets/13098244/b0d3b079-d34e-4732-bec3-d6eacab1133c)
Hello, I want to know which branch you use. I use branch `v1.0.1`, but meets the problem above with bad code.

**Comment by lgalabru** [comment]
@taoyouxian this looks like a different issue. could you share the commands that you're sending, along with configuration file? Thanks!

**Comment by taoyouxian** [comment]
> @taoyouxian this looks like a different issue. could you share the commands that you're sending, along with configuration file? Thanks!

Thanks for replying. I have fixed it by upgrading the Bitcoin version.

**Comment by lgalabru** [comment]
This is being worked on with https://github.com/hirosystems/ordhook/pull/200 and https://github.com/hirosystems/ordhook/pull/206

**Comment by mefrem** [comment]
@lgalabru should I update docs to include `ulimit` instruction?

**Comment by lgalabru** [comment]
The README already includes this instruction.
Will close this ticket, thanks @mefrem!
