### ISSUE TITLE
Cursed recursive inscription has different number on ord.io compared to ordinals.hiro.so

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/bitcoin-indexer#202]
**Describe the bug**
The short inscription number of this inscription is different between ord.io and ordinals.hiro.so

https://ordinals.hiro.so/inscription/81433a25e784366a7db917af98393be6eba232a03646e1fc072904fc3b8803b2i2 
![image](https://github.com/leather-wallet/extension/assets/33360391/d0a966a9-1d2d-427f-9edd-ef665480dac6)

https://www.ord.io/81433a25e784366a7db917af98393be6eba232a03646e1fc072904fc3b8803b2i2
![image](https://github.com/leather-wallet/extension/assets/33360391/7619e2e1-d99a-4005-b52f-08a06641e5c6)

I expect the short numbers to be the same between the explorers.

**Comment by lgalabru** [comment]
Addressed in [v2.0.0](https://github.com/hirosystems/ordhook/releases/tag/v2.0.0)
