### ISSUE TITLE
Support Bitcoin Testnet

### ISSUE THREAD

**Issue by 1921Aaron** [hirosystems/bitcoin-indexer#203]
I'm building on a test network and when running ordhook service start --post-to=http://localhost:3000/api/events --config-path=./Ordhook.toml it says `Nov 14 10:29:24.226 ERRO Error standardizing block: error retrieving prevout for transaction 4a2750823d8b3111f7ceb0ab258abcdf10d481e78c7f5c3052888dc269ae4616, input #0 (block #2538412)`

**Comment by lgalabru** [comment]
Hi @1921Aaron! Unfortunately this project is not actively against Testnet. Ordinals specifications are **very** loosely defined, and versions of `ord` have been conflicting with itself on almost every single release. 
We're focusing on Mainnet for now, which is already a non trivial challenge.

**Comment by lgalabru** [comment]
Addressed with https://github.com/hirosystems/ordhook/pull/208

**Comment by 1921Aaron** [comment]
@lgalabru sir,Nov 27 07:04:47.818 ERRO Error standardizing block: error retrieving prevout for transaction 707c597ef9d14d76403737b00307e63bd1d5ba1118d85e138ee24e39cba9a83f, input #0 (block #2540634)
