### ISSUE TITLE
Support Jubilee 

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/bitcoin-indexer#207]

**Comment by MikaelBTC** [comment]
Cause BRC-20 is moving to Jubilee, can ordhook support Jubilee before the upgrade? Thank you very much.

**Comment by lgalabru** [comment]
Hi @MikaelBTC! We are in the process of testing and finalizing the release of Ordhook. 
Note that if you're using Ordhook exclusively for BRC20, you will be perfectly fine with the current version. Yes the BRC20 indexers are adopting the latest release 0.14, but they will all be basing their indexing using taking into account the `vindicated` flag - meaning they are completely ignoring the actual changes coming with the Jubilee.

**Comment by MikaelBTC** [comment]
> Hi @MikaelBTC! We are in the process of testing and finalizing the release of Ordhook. Note that if you're using Ordhook exclusively for BRC20, you will be perfectly fine with the current version. Yes the BRC20 indexers are adopting the latest release 0.14, but they will all be basing their indexing using taking into account the `vindicated` flag - meaning they are completely ignoring the actual changes coming with the Jubilee.

Thank you very much @lgalabru, also which ordhook version will work same as Jubilee? V1.1.3 or V1.2.0 or both?

**Comment by lgalabru** [comment]
Jubilee support added in [v2.0.0](https://github.com/hirosystems/ordhook/releases/tag/v2.0.0)

**Comment by lgalabru** [comment]
@MikaelBTC If you'd like to stay on v1, 1.2.0 would probably best.

**Comment by MikaelBTC** [comment]
> @MikaelBTC If you'd like to stay on v1, 1.2.0 would probably best.

Thank you so much for explaining.
