### ISSUE TITLE
Out of memory when downlaod "mainnet-ordhook-sqlite-latest.tar.gz"

### ISSUE THREAD

**Issue by z0y1** [hirosystems/bitcoin-indexer#212]
Out of memory when downlaod "mainnet-ordhook-sqlite-latest.tar.gz"

$ ordhook scan blocks 767430 767753 --config-path=./Ordhook.toml
Nov 23 10:40:48.002 INFO Unable to retrieve hord.sqlite file locally
Nov 23 10:40:48.003 INFO Downloading https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest.tar.gz
=> https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest.tar.gz
[====================================================>.....] (19719829229/21581459625)killed

![image](https://github.com/hirosystems/ordhook/assets/1248666/94b396e2-efb4-4cb4-b6cc-c4da1e7980ce)

**Comment by lgalabru** [comment]
Hey @z0y1! Thanks for creating this issue. When this definitely needs to be fixed, in the meantime you could manually download this file using curl / wget, move it to the right dir and then launch `ordhook`.

**Comment by lgalabru** [comment]
The command 
```
ordhook scan blocks 767430 767753 --config-path=./Ordhook.toml
```
is indicating that an outdated version is being used.

```
ordhook scan blocks --interval 767430:767753 --config-path=./Ordhook.toml
```
since is the new syntax.

@z0y1 feel free to reopen this issue if you're still experiencing this after updating the version of `ordhook` being ran.

**Comment by tapstoone** [comment]
> move it to the right dir and then

hi, i downloaded by wget. but what's the  `right dir`?
