### ISSUE TITLE
unable to open hord.rocksdb: IO error....No locks available 

### ISSUE THREAD

**Issue by InfoIsland** [hirosystems/bitcoin-indexer#216]
Hi Team, I'm seeing this error: 

```
ERRO unable to open hord.rocksdb: IO error: lock hold by current process, acquire time 1700832341 acquiring thread 1826032: /usr/local/etc/ordhook/data/hord.rocksdb/LOCK: No locks available
```
![screenshot-2023-11-26-17 56 06@2x](https://github.com/hirosystems/ordhook/assets/146526844/2b0d6db4-c3bf-4896-ab41-3fc300e339f8)

Any clues or any additional info I can provide for debugging?

**Comment by lgalabru** [comment]
@InfoIsland this log is usually not a good sign - it would happen if you interacted with the ordhook cli, while also running it as a service.
Can you maybe try to `rm` that lock file? Ultimately you might end up with a corrupted db.

**Comment by InfoIsland** [comment]
@lgalabru I'm not using ordhook cli when starting it. I started the ordhook by downloading the latest archive file. 

I deleted everything and restarted them, it is working ok now. It failed for the first and second time, but works at 3rd time.

**Comment by lgalabru** [comment]
Ok, strange. Could you make sure that you're running the latest https://github.com/hirosystems/ordhook/releases/tag/v1.1.2?

**Comment by InfoIsland** [comment]
running `v1.1.2` works fine. I was running `v0.6.1`. thanks for the help, closing this issue.
