### ISSUE TITLE
thread 'Block data compression' panicked at 'called `Option::unwrap()

### ISSUE THREAD

**Issue by mszczepanik1337** [hirosystems/bitcoin-indexer#227]
I've installed ordhook on my local computer and i'm trying to run this as a service. On the beginning everything was looking fine, but further i was i've encountered more errors. Currently im +- 190k block and my console looks like on screen. 

![Screenshot 2023-12-07 at 14 40 07](https://github.com/hirosystems/ordhook/assets/72571212/e03b09aa-64f8-4d18-9708-53ac45b915c1)

My config:
```
[storage]
working_dir = "ordhook"

# The Http Api allows you to register / deregister
# dynamically predicates.
# Disable by default.
#
# [http_api]
# http_port = 20456
# database_uri = "redis://localhost:6379/"

[network]
mode = "mainnet"
bitcoind_rpc_url = "xxx"
bitcoind_rpc_username = "xxx"
bitcoind_rpc_password = "xxx"
# Bitcoin block events can be received by Chainhook
# either through a Bitcoin node's ZeroMQ interface,
# or through the Stacks node. Zmq is being
# used by default:
bitcoind_zmq_url = "tcp://xxx:29000"
# but stacks can also be used:
# stacks_node_rpc_url = "http://0.0.0.0:20443"

[limits]
max_number_of_bitcoin_predicates = 100
max_number_of_concurrent_bitcoin_scans = 100
max_number_of_processing_threads = 2000
bitcoin_concurrent_http_requests_max = 64
max_caching_memory_size_mb = 8000
```

# Disable the following section if the state
# must be built locally
[bootstrap]
download_url = "https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest"

[logs]
ordinals_internals = true
chainhook_internals = true

Tried this on 2 machines and both have similar issues - did i missed something?

**Comment by 4ker-dep** [comment]
Please see: [this tip](https://github.com/hirosystems/ordhook/issues/232#issuecomment-1858051566) for a solution.
