### ISSUE TITLE
Different ordinals number from ordinals.com

### ISSUE THREAD

**Issue by MikaelBTC** [hirosystems/bitcoin-indexer#229]
Hi, I am running the ordhook server with version: v1.0.3 and v1.1.3, they all have the wrong inscription number of inscription id: f34df2c53c3411c452ebfdef6537fd14546630fca0c425d1a1641d7bf8211008i0, same problem of your server: https://ordinals.hiro.so/inscription/f34df2c53c3411c452ebfdef6537fd14546630fca0c425d1a1641d7bf8211008i0. 

We all have the number: #46625971, but on ordinals.com(v0.9.0) the number is #46625972.

Thank you very much!

**Comment by lgalabru** [comment]
Looking into this.

**Comment by MikaelBTC** [comment]
Thanks lgalabru. I think I found the problem, this inscription should not be cursed: https://ordinals.hiro.so/inscription/29759ec49d0a29ef5000a0ca5eeb1b46c4134e8365acb345d54e6d68edd96abei0

**Comment by lgalabru** [comment]
The patch is available [here](https://github.com/hirosystems/ordhook/pull/230), I'll be doing some more testing in the next days.
Note: this require a full re-index.

**Comment by lgalabru** [comment]
Addressed in https://github.com/hirosystems/ordhook/releases/tag/v2.0.0
