### ISSUE TITLE
db sync gets stuck

### ISSUE THREAD

**Issue by GuutBoy** [hirosystems/bitcoin-indexer#232]
Running `ordhook db sync --config-path=./Ordhook.toml`

Seems to get stuck after a few thousand blocks. It outputs like below : 
```
....
Dec 15 10:56:47.970 INFO Block #50072 saved to disk
Dec 15 10:56:47.970 INFO Block #50088 saved to disk
Dec 15 10:56:47.970 INFO Block #50104 saved to disk
Dec 15 10:56:47.970 INFO Block #50120 saved to disk
Dec 15 10:56:47.970 INFO Block #50136 saved to disk
Dec 15 10:56:47.970 INFO Block #50152 saved to disk
Dec 15 10:56:47.971 INFO Block #50167 saved to disk
Dec 15 10:56:47.971 INFO Block #50183 saved to disk
Dec 15 10:56:47.971 INFO Block #50200 saved to disk

```
But then does not proceed.

I also see this line being output which may be a related problem:

```thread 'Block data compression' panicked at 'called `Option::unwrap()` on a `None` value', components/ordhook-core/src/db/mod.rs:1583:59```

**Comment by 4ker-dep** [comment]
You probably need to upgrade your bitcoin core to a newer version that supports RPC method 'getblock' with verbosity with the value of 3. It should work with at least v25 or higher.

**Comment by GuutBoy** [comment]
Upgrading to at least v25 seems to have solved this. Thanks.
