### ISSUE TITLE
db sync unable to retrieve Bitcoin chain tip

### ISSUE THREAD

**Issue by GuutBoy** [hirosystems/bitcoin-indexer#234]
Running `ordhook db sync --config-path=./Ordhook.toml` to sync the db I get this error 

```
ERRO unable to retrieve Bitcoin chain tip (JSON-RPC error: transport error: unexpected HTTP code: 400)
```

I previously posted this issue https://github.com/hirosystems/ordhook/issues/232 where the sync would get stuck after saving a few thousand blocks to disk. This seemed to be fixed by upgrading the bitcoin core to version 25.0. But now after ordhook saving blocks up to ~820000 to disk  this error is appearing. Any idea what might be causing this?

**Comment by GuutBoy** [comment]
Ah, figured it out. Bitcoin core was configured wrong.

**Comment by sun1912** [comment]
What configured wrong is?
