### ISSUE TITLE
Waiting for ZMQ messages from bitcoind

### ISSUE THREAD

**Issue by levi0522** [hirosystems/bitcoin-indexer#236]
Dec 28 15:42:42.863 INFO Pipeline successfully processed sequence of blocks (823282 to 823284)
Dec 28 15:42:42.938 INFO Database up to date, service will start streaming blocks
Dec 28 15:42:43.180 INFO Observing Bitcoin chain events via ZeroMQ: tcp://0.0.0.0:18543
Dec 28 15:42:43.180 INFO Listening on port 20456 for chainhook predicate registrations
Dec 28 15:42:43.207 INFO Waiting for ZMQ connection acknowledgment from bitcoind
Dec 28 15:42:43.207 INFO Waiting for ZMQ messages from bitcoind

**Comment by lgalabru** [comment]
Hey there! These are the logs when `ordhook` is launching. it'll be waiting for some blocks notifications emitted by `bitcoind`.
Feel free to re-open your issue if you have a question :).
