### ISSUE TITLE
Inscription number not matched with ordinals.com on v2.0.0

### ISSUE THREAD

**Issue by MikaelBTC** [hirosystems/bitcoin-indexer#244]
I started a new ordhook v2.0.0 server, reloaded all the data from the beginning. But I got the mis-matched inscription number: 6d9f78ebf5ad60df99a76fcc21bbbfb09c83c82c80c84140b0e52effee2dd0c4i0, #53666689 from ordhook but from #53681848 ordinals.com. I think many inscriptions are mis-matched. 

logs: 
Jan 08 00:42:35.562 INFO Inscription 6d9f78ebf5ad60df99a76fcc21bbbfb09c83c82c80c84140b0e52effee2dd0c4i0 (#53666689) detected on Satoshi 1877042280052473 (block #824802, 3879 transfers)

Thank you very much!

**Comment by lgalabru** [comment]
Hi @MikaelBTC,
We caught some issues at the time of the Jubilee block time and published some hot patches that are still in a branch.
I'll publish a 2.0.1 in the next hours.

https://ordinals.hiro.so/inscription/6d9f78ebf5ad60df99a76fcc21bbbfb09c83c82c80c84140b0e52effee2dd0c4i0
https://ordinals.com/inscription/6d9f78ebf5ad60df99a76fcc21bbbfb09c83c82c80c84140b0e52effee2dd0c4i0

**Comment by MikaelBTC** [comment]
Thank you very much for your effort.

**Comment by MikaelBTC** [comment]
> I started a new ordhook v2.0.0 server, reloaded all the data from the beginning. But I got the mis-matched inscription number: 6d9f78ebf5ad60df99a76fcc21bbbfb09c83c82c80c84140b0e52effee2dd0c4i0, #53666689 from ordhook but from #53681848 ordinals.com. I think many inscriptions are mis-matched.
> 
> logs: Jan 08 00:42:35.562 INFO Inscription 6d9f78ebf5ad60df99a76fcc21bbbfb09c83c82c80c84140b0e52effee2dd0c4i0 (#53666689) detected on Satoshi 1877042280052473 (block #824802, 3879 transfers)
> 
> Thank you very much!

I found the problem, the inscription number in the log is as same as the number from ord v0.9.0, I am not sure the number from the ord v0.14 is correct, I think you can log both the number in ord v0.9 and v0.14.

**Comment by lgalabru** [comment]
@MikaelBTC could you give a shot to https://github.com/hirosystems/ordhook/releases/tag/v2.0.1?

**Comment by lgalabru** [comment]
Note that you'll have to rollback the segment of blocks indexed since Jubilee so something along the lines:

```console
$ ordhook db drop 824544 <tip> --config-path ...
```

**Comment by MikaelBTC** [comment]
> @MikaelBTC could you give a shot to https://github.com/hirosystems/ordhook/releases/tag/v2.0.1?

Sure, I will try it. Thank you very much.

**Comment by MikaelBTC** [comment]
@lgalabru I found another one with wrong number: 54025106 on v2.0.1, but the right one is 54025105. This is the first time I found the bigger inscription number in ordhook.

logs:
Jan 10 04:37:20.850 INFO Inscription 31363e0a69b405c1ae4dc914a7d4c014b67bd4988b231285557c5cdb09b7727ei0 (#54025106) detected on Satoshi 1218205082869518 (block #825090, 909 transfers)

Thank you very much!

**Comment by MikaelBTC** [comment]
> @lgalabru I found another one with wrong number: 54025106 on v2.0.1, but the right one is 54025105. This is the first time I found the bigger inscription number in ordhook.
> 
> logs: Jan 10 04:37:20.850 INFO Inscription 31363e0a69b405c1ae4dc914a7d4c014b67bd4988b231285557c5cdb09b7727ei0 (#54025106) detected on Satoshi 1218205082869518 (block #825090, 909 transfers)
> 
> Thank you very much!

I found the root of this problem, which is in one block, the order of inscriptions is wrong, not only the inscription number. 
This one: 9b2364e642a36fa59f5990e987ea904c2a6cfe8a169f16af6a990a37d069ceb6i0(54025030, should be 54025027), it was inserted before: e381d494e37da3bcddd6fcacb0edea17bddbc377f29be1ff45012450ded534c2i0(54025031, should be 54025030). 

Thank you very much.

**Comment by lgalabru** [comment]
Hey @MikaelBTC, yes I am aware of this issue, I believe this is an issue in `ord` that I'm tracking and discussing here: https://github.com/ordinals/ord/issues/2967

**Comment by MikaelBTC** [comment]
> Hey @MikaelBTC, yes I am aware of this issue, I believe this is an issue in `ord` that I'm tracking and discussing here: [ordinals/ord#2967](https://github.com/ordinals/ord/issues/2967)

Thank you! Let's wait for the ord. 
Also, I think even if it is an issue of ord, ordhook can show the same result of ord, because the other indexers did this.

**Comment by MikaelBTC** [comment]
Hi @lgalabru, can you tell me if I use the ordhook v2.0.1 for brc-20 indexer, what is the difference from ord v0.14.1? Will they have difference balance for the same ticker and same address?

**Comment by lgalabru** [comment]
from a pure brc20 point of view, you should be fine.

**Comment by MikaelBTC** [comment]
> from a pure brc20 point of view, you should be fine.

That is cool, thank you very much.

**Comment by ybeetle8** [comment]
I've found that Number doesn't match here either, I'm on 2.0.1.

**Comment by ybeetle8** [comment]
Inscription dfead85b8136d8467d6abc91db00d92ff5294dd75c2f56a194112dd6674f7bd6i0 revealed at block #826789 (inscription_number 56884438, ordinal_number 1694301393173832)
v2.0.1
ordinals.com  Inscription 56794826

**Comment by lgalabru** [comment]
Addressed in `v2.1.0`, in the process of being released.
