### ISSUE TITLE
Stuck on warning "no such table: observers"

### ISSUE THREAD

**Issue by GuutBoy** [hirosystems/bitcoin-indexer#249]
When running 

`ordhook scan blocks --interval [first_block]:[last_block] --post-to=http://localhost:3000 --config-path=./Ordhook.toml`

The first block appears to be processed correctly, but then I see 
```
WARN unable to query hord.sqlite: no such table: observers
````
output over and over and no progress seems to be made. 

Any idea what causes this?

**Comment by lgalabru** [comment]
Hi @GuutBoy! Which version of `ordhook` are you running?

**Comment by GuutBoy** [comment]
I cloned and installed the latest version. I.e. ran 
```
$ git clone https://github.com/hirosystems/ordhook.git
$ cd ordhook
$ cargo ordhook-install
```
As directed in the readme.

**Comment by GuutBoy** [comment]
Its not wrong either. There is no `observers` table in `ordhook/hord.sqlite`

**Comment by lgalabru** [comment]
Good catch, thanks! 
To be fixed in https://github.com/hirosystems/ordhook/pull/250

**Comment by GuutBoy** [comment]
#250 is in draft status. Is there a work around that can be applied until it is merged?

**Comment by GuutBoy** [comment]
I tried check out that branch but it did not work. Now I just repeatedly get this warning 
```
WARN unable to prepare query hord.sqlite: no such column: ordinal_number
```

**Comment by GuutBoy** [comment]
Starting with a new data directory and doing a `db sync` appears to work. But it starts from block 0 (rather than downloading the bootstrap file) and appears to take hours and hours to finish.

**Comment by GuutBoy** [comment]
@lgalabru this thing metioned above with this warning blocking the progress 

```WARN unable to prepare query hord.sqlite: no such column: ordinal_number```

Seems to be because the `locations` table in the snapshot db is not compatible with the changes in #250.

**Comment by lgalabru** [comment]
Correct. We are currently working on producing a new snapshot, should be ready by EOD.

**Comment by smcclellan** [comment]
This has been resolved, available in `develop` branch.

**Comment by GuutBoy** [comment]
Correct, the recent version in `develop` solves this for me.
