### ISSUE TITLE
Waiting for ZMQ connection acknowledgment from bitcoind  ,  been waiting.

### ISSUE THREAD

**Issue by ybeetle8** [hirosystems/bitcoin-indexer#251]
Jan 14 02:27:48.936 INFO Block #2572752 processed, revealed 1 inscriptions [860612] and 1 transfers
Jan 14 02:27:48.953 INFO Pipeline successfully processed sequence of blocks (2572698 to 2572752)
Jan 14 02:27:48.981 INFO Database up to date, service will start streaming blocks
Jan 14 02:27:49.367 INFO Observing Bitcoin chain events via ZeroMQ: tcp://127.0.0.1:28332
Jan 14 02:27:49.384 INFO Waiting for ZMQ connection acknowledgment from bitcoind
Jan 14 02:27:49.384 INFO Waiting for ZMQ messages from bitcoind

I've been waiting here for a new block of data, and I don't see a push.

my  bitcoin.conf:
testnet=1
dbcache=10240
txindex=1
daemon=1
server=1
rest=1
whitebind=127.0.0.1:8333
rpcallowip=0.0.0.0/0
rpcuser=user
rpcpassword=password999
zmqpubrawtx=tcp://*:28332
zmqpubrawblock=tcp://*:28332

**Comment by lgalabru** [comment]
@ybeetle8 I would make sure that your bitcoind install was compiled with zmq support.

**Comment by ybeetle8** [comment]
Thanks, I'll test if bitcoind install compiles with zmq support.

**Comment by 0xAnduin** [comment]
Same,have you found a way to solve it?

**Comment by lgalabru** [comment]
Feel free to re-open this issue with more logs and more details if you're still having some troubles.
