### ISSUE TITLE
Post from block #775203 when starting service with post-to parameter

### ISSUE THREAD

**Issue by MikaelBTC** [hirosystems/bitcoin-indexer#252]
I started ordhook server V2.0.1 like this: ordhook service start --post-to=http://post_to_server/ --config-path=./Ordhook.toml. In V1.3 it will post the latest processed block to the post-to server, but in V2.0.1 it posted from block #775203. I can not figure out if it is a bug or new feature, please check it. And I want to know how to post the latest processed block to the server but not from block #775203. 
Thank you very much!

**logs:** 
Jan 16 07:13:28.919 INFO Block received from pre-processor
Jan 16 07:13:28.953 INFO Evaluating 0 bitcoin chainhooks registered
Jan 16 07:13:28.953 INFO 0 bitcoin chainhooks positive evaluations
Jan 16 07:13:28.953 INFO 0 bitcoin chainhooks will be triggered
Jan 16 07:13:28.953 INFO 0 bitcoin chainhooks to deregister
Jan 16 07:13:29.602 INFO Processing block #775203 through http://post_to_server/ predicate revealed 21 new inscriptions [5012, 5013, 5014, 5015, 5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032] and 0 transfers
Jan 16 07:13:29.624 INFO Trigger http://post_to_server/ successful
Jan 16 07:13:30.457 INFO Processing block #775204 through http://post_to_server/ predicate revealed 5 new inscriptions [5033, 5034, 5035, 5036, 5037] and 0 transfers
Jan 16 07:13:30.490 INFO Trigger http://post_to_server/ successful
Jan 16 07:13:31.442 INFO Processing block #775205 through http://post_to_server/ predicate revealed 0 new inscriptions [] and 2 transfers
Jan 16 07:13:31.459 INFO Trigger http://post_to_server/ successful
Jan 16 07:13:32.228 INFO Processing block #775206 through http://post_to_server/ predicate revealed 8 new inscriptions [5038, 5039, 5040, 5041, 5042, 5043, 5044, 5045] and 2 transfers
Jan 16 07:13:32.249 INFO Trigger http://post_to_server/ successful
Jan 16 07:13:33.007 INFO Processing block #775207 through http://post_to_server/ predicate revealed 11 new inscriptions [5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056] and 0 transfers
Jan 16 07:13:33.033 INFO Trigger http://post_to_server/ successful
Jan 16 07:13:33.924 INFO Processing block #775208 through http://post_to_server/ predicate revealed 7 new inscriptions [5057, 5058, 5059, 5060, 5061, 5062, 5063] and 1 transfers
Jan 16 07:13:33.940 INFO Trigger http://post_to_server/ successful

**Comment by lgalabru** [comment]
Hey @MikaelBTC! This is a feature, but I think you're right and we should allow the developers to set their first height.
I'll add a command flag for this, in the meantime you can tweak you `observers.sqlite` db and manually set the block height of the observer you registered to the one you'd like.

**Comment by MikaelBTC** [comment]
> Hey @MikaelBTC! This is a feature, but I think you're right and we should allow the developers to set their first height. I'll add a command flag for this, in the meantime you can tweak you `observers.sqlite` db and manually set the block height of the observer you registered to the one you'd like.

Thanks @lgalabru . I think we really need the command flag for the first height.

**Comment by devlancer412** [comment]
Hi @MikaelBTC  I have some problem with post-to param. Could you share post endpoint definition?

**Comment by tiehoo** [comment]
> Hey @MikaelBTC! This is a feature, but I think you're right and we should allow the developers to set their first height. I'll add a command flag for this, in the meantime you can tweak you `observers.sqlite` db and manually set the block height of the observer you registered to the one you'd like.

Hi Igalabru, 
I also need to set the start block, may I ask how can I set it in observers.sqlite. I tried to query it, it only has an empty table called observers. Please kind point out. Thanks a lot!

**Comment by tiehoo** [comment]
> > Hey @MikaelBTC! This is a feature, but I think you're right and we should allow the developers to set their first height. I'll add a command flag for this, in the meantime you can tweak you `observers.sqlite` db and manually set the block height of the observer you registered to the one you'd like.
> 
> Hi Igalabru, I also need to set the start block, may I ask how can I set it in observers.sqlite. I tried to query it, it only has an empty table called observers. Please kind point out. Thanks a lot!

It seems, chainhook uuid is the key, but I don't know how to find out which uuid I should insert into the observers table. Thanks!
