### ISSUE TITLE
start service always show Completed ordinal number retrieval

### ISSUE THREAD

**Issue by yyyfor** [hirosystems/bitcoin-indexer#253]
<img width="885" alt="image" src="https://github.com/hirosystems/ordhook/assets/9663620/411c06e5-6f0b-42e6-9df2-c75dd655fe8d">

When start service, the log always show as above. The log exists for several days and no progress on starting. Is it correct?

Thanks

**Comment by lgalabru** [comment]
Hi @yyyfor. Yes, when you start the ordhook, it needs to catchup with the chain tip, and make sure that all the inscriptions from the past has been correctly indexed.

**Comment by yyyfor** [comment]
Hi @lgalabru Thanks for your reply. May I ask how long does it usually take? I've been scanning for almost two weeks
