### ISSUE TITLE
Archive sqlite and rocksdb is out of date[duplicated previous data]

### ISSUE THREAD

**Issue by sshuair** [hirosystems/bitcoin-indexer#255]
hi, teams. really appreciate you guys build this awesome project. i have checked the archive data. it seems not update after 2024-01-10, all the file is duplicate.

**Comment by lgalabru** [comment]
Thanks for cheering up @sshuair! 
I believe this issue was addressed, I was able to download new archives recently.
Make sure you're using the latest release (2.1.0 - in the process of being published).

**Comment by lgalabru** [comment]
Feel free to re-open this issue with more logs if you're still having some trouble.
