### ISSUE TITLE
Unable to process transaction {deae1ae1d9d377ab828b13a3847d0b738caa99f080a3287fde43ede8e752cd28} detected after {2570891} iterations. Manual investigation required

### ISSUE THREAD

**Issue by ss22219** [hirosystems/bitcoin-indexer#262]
Error running on testnet [deae1ae1d9d377ab828b13a3847d0b738caa99f080a3287fde43ede8e752cd28](https://mempool.space/testnet/tx/deae1ae1d9d377ab828b13a3847d0b738caa99f080a3287fde43ede8e752cd28)

`
sats_out += ordinal_offset > sats_in
`

**Comment by lgalabru** [comment]
This issue was addressed in v2.1.0, in the process of being released.
