### ISSUE TITLE
WARN unable to retrieve block hash #0: will retry in a few seconds (attempt #4).

### ISSUE THREAD

**Issue by ChristianSchneeweiss** [hirosystems/bitcoin-indexer#263]
Hello,
For local development I am trying to use the bitcoin node running on a server in my tailnet. The rpc_url is working but I cant get the bitcoind_zmq_url to connect to the server. I get the error message WARN unable to retrieve block hash #0: will retry in a few seconds (attempt #4). The port is reachable indicated by tailscale and I tried everything on tailscale side

**Comment by ChristianSchneeweiss** [comment]
Tested it also without tailnet, just using the ip of the server and allowing the 18543 port with ufw. Still not working

**Comment by lgalabru** [comment]
Dependending on how you got bitcoind installed on your machine, you may or may not have zeromq enabled - it's an option that needs to be enabled at compilation time.

**Comment by ChristianSchneeweiss** [comment]
Ordhook + bitcoind is working as expected on the server. but using the bitcoind **from the server** for my local ordhook is not working

**Comment by lgalabru** [comment]
Ah yeah, you might have to make your zmq port public, or bind your bitcoind zmq port to publicly routable port or something - not something that I'd recommend.
