### ISSUE TITLE
Wrong owner address on some inscriptions

### ISSUE THREAD

**Issue by ismyhc** [hirosystems/bitcoin-indexer#264]
I've noticed a few inscriptions that have the wrong owner address.

```
curl -L 'https://api.hiro.so/ordinals/v1/inscriptions/39399e536443446eda3f26ce7038178ec3b69157f38eaed19caea4614aabaf62i10' \
-H 'Accept: application/json'
```

Returns owner address as: **bc1pugucxk7chk8phv5vatruhd4ngwefml06m2evraw9eruanwsvmd2s46zlhe**

However, ord indicates the address as: **bc1pardmwnx0ehtuu62q03nvlw9uglz4rvzmv9a43uq9tf99rtra897st3mxst**

```
https://ordinals.com/inscription/39399e536443446eda3f26ce7038178ec3b69157f38eaed19caea4614aabaf62i10
```

I noticed the same issue on another as well. I also checked transfers for this and it doesn't include a transfer to the address that old indicates is owner.

Curious if anyone has seen this issue before.

**Comment by lgalabru** [comment]
Thanks for opening this issue @ismyhc. This issue was in our radar, and addressed in v2.1.0 - in the process of being released.
