### ISSUE TITLE
Using ordhook-sdk-js

### ISSUE THREAD

**Issue by devlancer412** [hirosystems/bitcoin-indexer#265]
I've got this error when install @hirosystems/ordhook-sdk-js. Please give me solution.

![image](https://github.com/hirosystems/ordhook/assets/101313445/9f19ac32-2f30-438d-a7ca-e5b53750fb87)

**Comment by sabbyanandan** [comment]
Hi, @devlancer412! Glad to see you're trying to use Ordhook. Could you share a little more context as to the steps you followed and how you ended up with this error? The more details, the better it would be for us to review/troubleshoot.

**Comment by devlancer412** [comment]
I've run bitcoin core and was going to get event from this daemon with ordhook library. I'm using NestJs backend and just tried to install this package to my backend

**Comment by sabbyanandan** [comment]
@devlancer412: Alright, that is helpful. 

@lgalabru: FYI.

**Comment by lgalabru** [comment]
hey @devlancer412!
This javascript package is very promising, but also ver experimental at this point - pretty much a wip. 
We're not using it yet, it is a work in progress so unless you're familiar with Rust, Nodejs, [NAPI](https://napi.rs) and ready to contribute actively on this component, I would advise against going down that route :).

**Comment by devlancer412** [comment]
So you mean I can't use that package for now? If so could you let me know detail about callback endpoint of ordhook server?

**Comment by lgalabru** [comment]
You can use that package but you'll be on your own, the issues you'd end facing are uncharted territory.
The alternative is to use ordhook-cli and register an HTTP observer, as described in our documentation.

**Comment by devlancer412** [comment]
https://github.com/hirosystems/docs/issues/615

@lgalabru Could you check about this?
