### ISSUE TITLE
When scanning an inscription:  no such column: inscription_id

### ISSUE THREAD

**Issue by tegaget** [hirosystems/bitcoin-indexer#278]
I get this when I try scanning any inscription:

```
Mar 08 05:06:36.530 INFO Basing ordinals evaluation on database /media/ssd/ordhook/ordhook/hord.sqlite
Inscription 3700db179a781db483487f9701c74cc333cd41798de250d07978bb9b4494d886i0 revealed at block #793345 (inscription_number 11108176, ordinal_number 45086530987)
Mar 08 05:06:36.533 WARN unable to prepare query SELECT offset, outpoint_to_watch, tx_index, block_height FROM locations WHERE inscription_id = ? ORDER BY block_height ASC, tx_index ASC: no such column: inscription_id
Mar 08 05:06:41.533 WARN unable to prepare query SELECT offset, outpoint_to_watch, tx_index, block_height FROM locations WHERE inscription_id = ? ORDER BY block_height ASC, tx_index ASC: no such column: inscription_id
Mar 08 05:06:46.533 WARN unable to prepare query SELECT offset, outpoint_to_watch, tx_index, block_height FROM locations WHERE inscription_id = ? ORDER BY block_height ASC, tx_index ASC: no such column: inscription_id
```

**Comment by lgalabru** [comment]
Hey @tegaget! I think the version of ordhook is outdated, you'll need to pull the latest changes and recompile ordhook, or use a more recent version of the docker image.
Feel free to re-open if the instructions above are not fixing your issues.

**Comment by tegaget** [comment]
I have compiled the last version(2.1.0) and the version before it(2.0.1).  However, when I compile and install it always says version 2.0.0.  I have cloned the rep and sure I am compiling correct version.  Are the latest changes in 2.1.0 or they are not yet merged into the current version?

How is the docker image related to this compilation?   I just compile the rep and run. 
Thanks.

**Comment by tegaget** [comment]
I viewed the snapshots on sqlite you have and those do not seem to have the column inscription id that ordhook is trying to find.  the downloaded snapshot https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest
seems incorrect table structure for the ordhook.

**Comment by liushmh** [comment]
I have same error, why this issue is closed?
@tegaget

**Comment by lgalabru** [comment]
@liushmh I have tested this setup a few times and interacted with multiple developers using this setup, everything seems functional.
I'd recommend removing your current install, recloning the repo, making sure that you're pulling the latest version of the code + make sure that you're not using this new version with outdated dbs.
