### ISSUE TITLE
Inaccurate Inscription Numbering in Ordhook Database

### ISSUE THREAD

**Issue by duyquoc1508** [hirosystems/bitcoin-indexer#294]
### Description:
I encountered an issue while running ordhook on my server. The problem arises with the archive database obtained from the link https://archive.hiro.so/.

After downloading the latest version of the ordhook archive (rocksdb + sqlite) and running it, I noticed that while the number of blocks increases as expected, the inscription numbering does not start from the end of the previous block (n - 1). Instead, it starts from the end of the previous two blocks (n - 2). Consequently, all inscription numbers for the following blocks become incorrect.

I downloaded the database from April 1, 2024, and encountered this issue. Below is a log snippet after starting the service:
```
{"msg">Index lines from block #837194 to block #837227","level":INFO","ts":"2024-04-01T09:48:38.066411037Z"}
```

### Expected Behavior:
The inscription numbering should start from the end of the previous block (n - 1) as per the standard behavior.

### Steps to Reproduce:

1. Download the latest version of the ordhook archive from the provided link.
2. Start ordhook services using the downloaded archive.
3. Observe the behavior of the inscription numbering in the database.

### Additional Information:

Version of ordhook archive used: [mainnet-ordhook-sqlite-24-alpine-20240401.tar.gz](https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-24-alpine-20240401.tar.gz)
Date of database download: April 1, 2024

### Screenshots/Logs:
![image](https://github.com/hirosystems/ordhook/assets/30165101/d313ea2b-4d1d-4f73-b286-8e639390b132)
![image](https://github.com/hirosystems/ordhook/assets/30165101/8d0bb59f-9b96-466b-892a-e0f6fb527fdd)

### Environment:

- Ordhook docker image: hirosystems/ordhook:2.1.0

Note: I would appreciate any assistance or insights into resolving this issue. Thank you!

**Comment by duyquoc1508** [comment]
We have identified the issue lying within the `sequence_metadata` table in the sqplite database restored from the archive.

It appears that the `sequence_metadata` table consistently lacks a record for the last block (n - 1), regardless of the database version. This deficiency causes ordhook to increment the `jubilee_inscription_number` based on the preceding block (n - 2), as block (n - 2) is currently recognized as the latest block. However, the correct behavior should involve the existence of a record for block (n - 1), which represents the latest block height.

As a result, the incorrect numbering of inscription numbers occurs due to this discrepancy in the database.

**Comment by duyquoc1508** [comment]
I've also discovered discrepancies in the HIRO API and the archive database, specifically regarding inscription numbering from block 837927 onwards. I suspect that the underlying issue mentioned earlier may be the root cause. This suspicion arises from the observation that the `sequence_metadata` table also lacks a record at block 837926.

To further illustrate this point, I conducted a small comparison exercise. I randomly selected an inscription ID from block 837930 (after 837927) and queried it against several other indexers. Here are the results:

Inscription ID: b3f51c7634e85f1c95d8f3c7fed0dabc8cb20b2dfafe495509bb6c6b51aeaa62i0

- docs.hiro.so
![image](https://github.com/hirosystems/ordhook/assets/30165101/c2544dfa-0f2e-4033-9055-b9e88ec79300)
- [geniidata.com](https://geniidata.com/ordinals/inscription/b3f51c7634e85f1c95d8f3c7fed0dabc8cb20b2dfafe495509bb6c6b51aeaa62i0?ref=CEKEXZ)
![image](https://github.com/hirosystems/ordhook/assets/30165101/b4143017-6039-4e7e-94d2-25f9b90cac3e)
- [ordinals.com](https://ordinals.com/inscription/b3f51c7634e85f1c95d8f3c7fed0dabc8cb20b2dfafe495509bb6c6b51aeaa62i0)
![image](https://github.com/hirosystems/ordhook/assets/30165101/57b59caf-5432-42b3-9987-543564913364)

These findings reinforce the possibility that the inconsistencies stem from the missing record in the `sequence_metadata` table at block 837926.
Your inscription number is less than other indexer system 6248 and 6248 is also the number inscription of block 837926.

I hope this additional information helps in further investigating and resolving the issue

**Comment by lgalabru** [comment]
Thanks for the investigation @duyquoc1508, I'll look into this today.

**Comment by lgalabru** [comment]
@duyquoc1508 you may have an email from in your spam folder :)

**Comment by quocndc98** [comment]
Hi @lgalabru ,
I apologize for missing your email. I'm curious to know if the results of your investigation align with my analysis above?
Thanks!

**Comment by lgalabru** [comment]
This issue is being addressed https://github.com/hirosystems/ordhook/pull/312

**Comment by lgalabru** [comment]
Addressed with latest!

<img width="1328" alt="Screenshot 2024-06-12 at 5 19 00 PM" src="https://github.com/hirosystems/ordhook/assets/87777/3009ace2-677b-4f81-ae44-6cd098410a01">
