### ISSUE TITLE
Inscription not found error, when the inscription exists

### ISSUE THREAD

**Issue by razr22** [hirosystems/bitcoin-indexer#295]
**Describe the bug**
I am trying to retrieve inscription information, and for the following inscription both Hiro's ordinal explorer returns an error and so does the api.

**To Reproduce**
Here are some relevant links:
https://api.hiro.so/ordinals/v1/inscriptions/9cb341c53d7be958d18531161e1ea0b5d21f0ec4589f5a396b821157bf300fe8i0
https://ordinals.hiro.so/inscription/9cb341c53d7be958d18531161e1ea0b5d21f0ec4589f5a396b821157bf300fe8i0
https://ordinals.com/inscription/9cb341c53d7be958d18531161e1ea0b5d21f0ec4589f5a396b821157bf300fe8i0
https://ordiscan.com/inscription/70016741

**Expected behavior**
Should return the inscription with the relevant information

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Chrome

**Comment by rafaelcr** [comment]
Transferring to ordhook because there seems to be an inconsistency with the indexing of that inscription. This is what ordhook sends to the API, note the `jubilee` inscription number which differs from ordinals.com cc @lgalabru 
```
{
  "inscription_revealed": {
    "content_bytes": "0x7b2270223a226272632d3230222c226f70223a227472616e73666572222c227469636b223a227a626974222c22616d74223a223130323536227d",
    "content_length": 58,
    "content_type": "text/plain;charset=utf-8",
    "curse_type": null,
    "delegate": "",
    "inscriber_address": "bc1pfwxn7wfwy26nsc69yx7xg65rk0gcc7ws4deala3l9p49nu8w7yhsmr5m5w",
    "inscription_fee": 8235,
    "inscription_id": "9cb341c53d7be958d18531161e1ea0b5d21f0ec4589f5a396b821157bf300fe8i0",
    "inscription_input_index": 0,
    "inscription_number": {
      "classic": 65837777,
      "jubilee": 70007973
    },
    "inscription_output_value": 546,
    "inscription_pointer": 0,
    "metadata": null,
    "metaprotocol": "",
    "ordinal_block_height": 837515,
    "ordinal_number": 1967197254083994,
    "ordinal_offset": 379083994,
    "parent": "",
    "satpoint_post_inscription": "9cb341c53d7be958d18531161e1ea0b5d21f0ec4589f5a396b821157bf300fe8:0:0",
    "transfers_pre_inscription": 0,
    "tx_index": 2491
  }
}
```

**Comment by razr22** [comment]
Hi, an instance of an improperly assigned owner if not an incorrect inscription. 

would appreciate a swift resolution to these issues, thanks.

Incorrect
https://ordinals.hiro.so/inscription/c5a7a9e8535a88999509a2e4c0c174f33b1ea43291c5808b06325638fb3c15eei645
https://api.hiro.so/ordinals/v1/inscriptions/c5a7a9e8535a88999509a2e4c0c174f33b1ea43291c5808b06325638fb3c15eei645

Correct
https://ordinals.com/inscription/c5a7a9e8535a88999509a2e4c0c174f33b1ea43291c5808b06325638fb3c15eei645

**Comment by razr22** [comment]
another mismatched inscription/inscription owner

https://ordinals.hiro.so/inscription/c5a7a9e8535a88999509a2e4c0c174f33b1ea43291c5808b06325638fb3c15eei1267
https://ordinals.com/inscription/c5a7a9e8535a88999509a2e4c0c174f33b1ea43291c5808b06325638fb3c15eei1267

**Comment by sabbyanandan** [comment]
@razr22: Apologies for the delay; please know that the team is actively looking into resolving it.

**Comment by razr22** [comment]
Ok, will have to look to other API providers for a solution until then.

**Comment by diwakergupta** [comment]
> Ok, will have to look to other API providers for a solution until then.

Sorry you feel that way. FWIW PR #300 will also fix this issue and is actively being tested, so we're very close.

**Comment by lgalabru** [comment]
I can see that the sequences are now aligned, thank you for your patience @razr22 🙏
Closing this issue.

**Comment by razr22** [comment]
> I can see that the sequences are now aligned, thank you for your patience @razr22 🙏 Closing this issue.

Awesome! Will take a look.
