### ISSUE TITLE
Different Owner Address Info Between Ordinals.com and Hiro Ordinals API

### ISSUE THREAD

**Issue by WooMai** [hirosystems/bitcoin-indexer#296]
**Describe the bug**

Inscription Number: 498457

On [ordinals.com](https://ordinals.com/inscription/498457), it shows this inscription is currently under the address `339PiqWnq6WcbXHb91PXfu4q18L9AiZDhK`.

But on the [Hiro API](https://api.hiro.so/ordinals/v1/inscriptions/498457), it shows `bc1qhhz3g6qsumlw8w6n4shwddcdjmthepyze5z748`.

**Screenshots**
![image](https://github.com/hirosystems/ordinals-api/assets/34209782/e84774a9-1568-4e0c-adcf-3e1580bf22b2)

![image](https://github.com/hirosystems/ordinals-api/assets/34209782/51854a37-4e91-4dcc-89fa-5a84cbfa6b2d)

**Additional context**
I noticed that this inscription was once spent as transaction fee, did this cause this problem?

Also, the inscription appears to have been used only once as tx fee ([ordiscan](https://ordiscan.com/inscription/498457)), but shows up 3 times in the [Hiro API](https://api.hiro.so/ordinals/v1/inscriptions/498457/transfers).

![image](https://github.com/hirosystems/ordinals-api/assets/34209782/486aab4b-2395-4512-a6fd-f76e1da1d50d)

![image](https://github.com/hirosystems/ordinals-api/assets/34209782/5029f4bb-0531-4207-9928-f7c29fce1e9f)

**Comment by WooMai** [comment]
This problem is also exists on [Ordinals Explorer](https://ordinals.hiro.so/inscription/863160c68d27db69caa6ffcf4c7c29dd0dabaf43ea549883a81a8857727f4795i0), compared with [ordiscan](https://ordiscan.com/inscription/498457).

**Comment by lgalabru** [comment]
Thanks @WooMai!
We're looking at an issue ordhook side. The transaction is spent in fee, in a coinbase that has more than one output. I'm working on a fix.

**Comment by lgalabru** [comment]
Fixed in #300
