### ISSUE TITLE
ERRO Block start / end block spec invalid

### ISSUE THREAD

**Issue by phill-beyond** [hirosystems/bitcoin-indexer#307]
After setting up testnet environment and freshly start db sync, got an block spec invalid error which looks like a bug.

ordhook db sync --config-path=./Ordhook.toml
Jun 01 01:45:19.298 INFO Indexing inscriptions from block #767430 to block #2819136
Jun 01 01:45:19.299 ERRO Block start / end block spec invalid

**Comment by phill-beyond** [comment]
I think the issue is: chainhook-sdk/src/utils/mod.rs
pub const MAX_BLOCK_HEIGHTS_ENTRIES: u64 = 1_000_000;
impl BlockHeights { 
    pub fn get_sorted_entries(&self) -> Result<VecDeque<u64>, BlockHeightsError> {
        let mut entries = VecDeque::new();
        match &self {
            BlockHeights::BlockRange(start, end) => {
                if start > end {
                    return Err(BlockHeightsError::StartLargerThanEnd);
                }
                if (end - start) > MAX_BLOCK_HEIGHTS_ENTRIES {
                    return Err(BlockHeightsError::ExceedsMaxEntries(
                        MAX_BLOCK_HEIGHTS_ENTRIES,
                        end - start,
                    ));
                }
 There is a MAX_BLOCK_HEIGHTS_ENTRIES, but my progress need to sync db from  #767430 to block #2819136 which is more than 1M.

**Comment by phill-beyond** [comment]
So the question comes to: How can I index on the testnet? Since no prebuilt db download available? Thanks!

**Comment by lgalabru** [comment]
Hi @phill-beyond, thanks for your feedback. I'll close this issue, as we're already tracking the lack of Testnet support here: https://github.com/hirosystems/ordhook/issues/292
