### ISSUE TITLE
How to set the log level?

### ISSUE THREAD

**Issue by GuutBoy** [hirosystems/bitcoin-indexer#328]
How do I set the log level? With the latest code on the `develop` branch I am getting a lot of DEBUG level logging I could do without. I dont see any thing in the config to change this.

**Comment by lgalabru** [comment]
Hey @GuutBoy! To get rid of the `DEBUG` logs, you need to compile the projet using the feature flag `release`
https://github.com/hirosystems/ordhook/blob/54296f6c033b46403781666b28daf1ed3ff2a158/dockerfiles/components/ordhook.dockerfile#L49

The level of logging can also be adjusted with your config file:
https://github.com/hirosystems/ordhook/blob/54296f6c033b46403781666b28daf1ed3ff2a158/components/ordhook-cli/src/config/generator.rs#L43-L44

**Comment by lgalabru** [comment]
Feel free to re-open this issue if we're missing something!
