### ISSUE TITLE
Understanding BRC-20 indexing

### ISSUE THREAD

**Issue by GuutBoy** [hirosystems/bitcoin-indexer#329]
I see that in a recent release you added BRC-20 indexing, and I see there is a `brc20.sqlite` database in the data directory now. But is brc-20 data also included in the data posted by ordhook to the http endpoint? Because I cant really find that.

**Comment by rafaelcr** [comment]
That's correct @GuutBoy but we still need to update the README for that. To receive BRC-20 data in your predicates, you should add the `meta_protocols` key like so:
```
			"if_this": {
				"scope": "ordinals_protocol",
				"operation": "inscription_feed",
				"meta_protocols": ["all"]
			},
```
If you're only interested in BRC-20 transactions and not the rest of ordinals set it to `brc20` instead of `all`

**Comment by GuutBoy** [comment]
This is not clear to me. Where do I add this? In the config file?

**Comment by rafaelcr** [comment]
@GuutBoy you should add this to your .toml file so ordhook indexes BRC-20
```
[meta_protocols]
brc20 = true
```
Then, when getting data through a predicate, add the `meta_protocols` key like this
```
"if_this": {
	"scope": "ordinals_protocol",
	"operation": "inscription_feed",
	"meta_protocols": ["all"]
},
```

**Comment by GuutBoy** [comment]
Sorry, I am not sure what "getting data through a predicate" means. Ordhook just POSTs a bunch of json to an end point?

**Comment by GuutBoy** [comment]
I guess maybe I am using `ordhook` wrong 😅

**Comment by rafaelcr** [comment]
@GuutBoy take a look at [this Chainhook README](https://github.com/hirosystems/chainhook/tree/develop?tab=readme-ov-file#development-workflow-for-bitcoin-chainhooks) which will explain how to use predicates, etc. This also applies to ordhook
