### ISSUE TITLE
ordhook service always stopped running [ERRO Unable to retrieve backward traversal result for inscription]

### ISSUE THREAD

**Issue by soliman9** [hirosystems/bitcoin-indexer#334]
I'm running `ordhook` as a service that it connects to a local bitcoin node to sync its data. The service run for some time then it suddenly stops with the following error message.

Here's the command used to start the service:
` ordhook service start --config-path=./Ordhook.toml`

The service is running on an Ubuntu OS VM with 8 CPUs, 16 GB RAM, 1 TB SSD. Also the `bitcoind` node is running on the same VM.

```
Jun 28 21:11:27.728 INFO Inscription 15738db301d227969b4f6e0ec8602044c4cc7d6904552f4dad5fafada27270eai0 (#139528) detected on Satoshi 288500992160301 (block #777201, 653 transfers)
Jun 28 21:11:27.729 INFO Inscription 5cea8027313fb590807810960d1f74ccd853b839b35aaffe1793119f124e697ci0 (#139529) detected on Satoshi 1652929295650008 (block #777201, 77 transfers)
Jun 28 21:11:27.730 ERRO Unable to retrieve backward traversal result for inscription 0xba9dd7b6201ad86a04ef19fa5378e9a70d5c09e90575416c4d31debe52957129
Jun 28 21:11:27.865 WARN Unable to find block #769886, will retry in 2.182s
Jun 28 21:11:27.873 WARN Unable to find block #554424, will retry in 2.43s
Jun 28 21:11:27.918 WARN Unable to find block #745386, will retry in 2.384s
```

**Comment by rafaelcr** [comment]
@soliman9 it looks like the `hord.rocksdb` state is corrupted in your setup... can you try downloading a new one from https://archive.hiro.so/mainnet/ordhook/ and trying again?

**Comment by soliman9** [comment]
> @soliman9 it looks like the `hord.rocksdb` state is corrupted in your setup... can you try downloading a new one from https://archive.hiro.so/mainnet/ordhook/ and trying again?

@rafaelcr Can I instead sync it locally?

**Comment by rafaelcr** [comment]
Sure, just clear the `hord.rocksdb` directory and any sqlite files and run `service start`

**Comment by habibitcoin** [comment]
@rafaelcr I just tried this using the latest archives, and then trying the 20240920 archives

Each time, I hit this issue:
```
Sep 20 17:27:19 ip-172-31-87-211 ordhook[3957448]: Sep 20 17:27:19.359 INFO Inscriptions data computation for block #860926 collected
Sep 20 17:27:19 ip-172-31-87-211 ordhook[3957448]: Sep 20 17:27:19.359 INFO Inscriptions data computation for block #860926 ended
Sep 20 17:27:19 ip-172-31-87-211 ordhook[3957448]: Sep 20 17:27:19.359 ERRO Unable to retrieve backward traversal result for inscription 0x8f24e1365658017220c603559f46f0b84748316dd8bf9261d3448cd8c2d61087
```

Any ideas?
